
points-folders:
  - './points'
rewards-folders:
  - './rewards'

# 是否使用 uuid 而非玩家名来识别玩家
# 离线模式服务器不推荐启用该选项
# auto - 自动 根据当前服务器的模式决定
# true - 在线模式 使用uuid识别玩家
# false - 离线模式 使用玩家名识别玩家
###########################################
#### 危险 : 插件正式投入使用后，请勿修改该选项
#### 否则将出现不可预料的问题。
###########################################
online-mode: auto

# 排行榜设置
rank:
  # 排行榜显示前多少位
  # 设置为 0 关闭排行榜
  top: 10
  # 多少秒刷新一次排行榜
  refresh-interval: 60
