name: SweetRewards
version: '${version}'
main: top.mrxiaom.sweet.rewards.SweetRewards
api-version: 1.13
softdepend:
  - PlaceholderAPI
authors: [ MrXiaoM ]
folia-supported: true
commands:
  sweetrewards:
    description: 'The main command of SweetRewards'
    aliases: [ sr, rewards ]
